#!/bin/bash -l
#SBATCH -A g2021012
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 08:00:00
#SBATCH -J genome_assembly_job
#SBATCH --mail-type=ALL
#SBATCH --mail-user lotta.rydin@telia.com

# Load modules
module load bioinfo-tools
module load canu

# Your commands
canu \
 -p genome_assembly -d ~/GenomeAnalysis_project/analyses/1_genome_assembly_res \
 genomeSize=3m \
 -pacbio ~/GenomeAnalysis_project/raw_data/genomics_data/PacBio/*
