#!/bin/bash -l
#SBATCH -A g2021012
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 1
#SBATCH -t 01:00:00
#SBATCH -J prokka_annotation_job
#SBATCH --mail-type=ALL
#SBATCH --mail-user lotta.rydin@telia.com

# Load modules
module load bioinfo-tools
module load prokka

# Commands
prokka --outdir ~/GenomeAnalysis_project/analyses/5_prokka_annotation/ \
--prefix annotation ~/GenomeAnalysis_project/analyses/1_genome_assembly_res/genome_assembly.contigs.fasta
