#!/bin/bash -l
#SBATCH -A g2021012
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 1
#SBATCH -t 02:00:00
#SBATCH -J trimmomatic_trimming_job
#SBATCH --mail-type=ALL
#SBATCH --mail-user lotta.rydin@telia.com

# Load modules
module load bioinfo-tools
module load trimmomatic

java -jar /sw/apps/bioinfo/trimmomatic/0.36/rackham/trimmomatic-0.36.jar \
PE ~/GenomeAnalysis_project/raw_data/transcriptomics_data/RNA-Seq_BH/trim_paired_ERR1797972_pass_1.fastq.gz \
~/GenomeAnalysis_project/raw_data/transcriptomics_data/RNA-Seq_BH/trim_paired_ERR1797972_pass_2.fastq.gz \
~/GenomeAnalysis_project/analyses/7_trimmomatic_trimming/output_forward_paired_ERR1797972.fq.gz \
~/GenomeAnalysis_project/analyses/7_trimmomatic_trimming/output_forward_unpaired_ERR1797972.fq.gz \
~/GenomeAnalysis_project/analyses/7_trimmomatic_trimming/output_reverse_paired_ERR1797972.fq.gz \
~/GenomeAnalysis_project/analyses/7_trimmomatic_trimming/output_reverse_unpaired_ERR1797972.fq.gz \
ILLUMINACLIP:/sw/apps/bioinfo/trimmomatic/0.36/rackham/adapters/TruSeq3-PE.fa:2:36:10:2:keepBothReads LEADING:3 TRAILING:3 MINLEN:36
