#!/bin/bash -l

#SBATCH -A g2021012
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 1
#SBATCH -t 05:00:00
#SBATCH -J bwa_BH_rna_alignment_job
#SBATCH --mail-type=ALL
#SBATCH --mail-user lotta.rydin@telia.com

# Load modules
module load bioinfo-tools
module load bwa

# Alingnment for BH
for i in {2..4}
do
	bwa aln ~/GenomeAnalysis_project/analyses/1_genome_assembly_res/genome_assembly.contigs.fasta \
	~/GenomeAnalysis_project/raw_data/transcriptomics_data/RNA-Seq_BH/trim_paired_ERR179797${i}_pass_1.fastq.gz \
	> ~/GenomeAnalysis_project/analyses/8_bwa_rna_align/aln_BH/aln_ERR179797${i}_pass_1.sai

	bwa aln ~/GenomeAnalysis_project/analyses/1_genome_assembly_res/genome_assembly.contigs.fasta \
	~/GenomeAnalysis_project/raw_data/transcriptomics_data/RNA-Seq_BH/trim_paired_ERR179797${i}_pass_2.fastq.gz \
	> ~/GenomeAnalysis_project/analyses/8_bwa_rna_align/aln_BH/aln_ERR179797${i}_pass_2.sai

	bwa sampe ~/GenomeAnalysis_project/analyses/1_genome_assembly_res/genome_assembly.contigs.fasta \
	~/GenomeAnalysis_project/analyses/8_bwa_rna_align/aln_BH/aln_ERR179797${i}_pass_1.sai \
	~/GenomeAnalysis_project/analyses/8_bwa_rna_align/aln_BH/aln_ERR179797${i}_pass_2.sai \
	~/GenomeAnalysis_project/raw_data/transcriptomics_data/RNA-Seq_BH/trim_paired_ERR179797${i}_pass_1.fastq.gz \
	~/GenomeAnalysis_project/raw_data/transcriptomics_data/RNA-Seq_BH/trim_paired_ERR179797${i}_pass_2.fastq.gz \
	> ~/GenomeAnalysis_project/analyses/8_bwa_rna_align/sampe_BH/aln-pe_ERR179797${i}.sam
done
